"""Front tire dynamics model.

This module contains functions for calculating the front tire dynamics based on
the model described in 'Dynamics And Control Of Drifting In Automobiles'
(Hindiyeh, 2013).

The implementation follows the original MATLAB model's equations while providing
JAX compatibility for GPU acceleration and automatic differentiation.
"""

import jax
import jax.lax as lax
import jax.numpy as jnp
from jax import jit


@jit
def calculate_front_tire_lateral_force(
    slip_angle: jax.Array, friction_coefficient: jax.Array, front_load: jax.Array, cornering_stiffness: jax.Array
) -> jax.Array:
    """Calculate the lateral force for the front tire given the slip angle.
    
    This is a JAX implementation of the MATLAB tire_dyn_f.m function from the original model.

    Args:
        slip_angle: Angle between the tire's heading and its actual direction of travel, in radians.
            (Engineering variable: alpha)
        friction_coefficient: Tire-road friction coefficient (dimensionless).
            (Engineering variable: mu)
        front_load: Normal load on the front tire in Newtons.
            (Engineering variable: load_f)
        cornering_stiffness: Tire cornering stiffness in N/rad.
            (Engineering variable: C_alpha)

    Returns:
        lateral_force: Lateral force generated by the front tire in Newtons.
            (Engineering variable: Fy)
    """
    # Handle extreme slip angles (> pi/2)
    adjusted_slip_angle = lax.cond(
        jnp.abs(slip_angle) > jnp.pi / 2,
        lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
        lambda angle: angle,
        slip_angle,
    )

    # Calculate the sliding limit angle (transition between regimes)
    sliding_limit_angle = jnp.arctan(3 * friction_coefficient * front_load / cornering_stiffness)

    # Calculate lateral force based on slip angle magnitude
    def calc_linear_region(angle: jax.Array) -> jax.Array:
        """Calculate lateral force in the linear (non-saturated) region."""
        return (
            -cornering_stiffness * jnp.tan(angle)
            + cornering_stiffness**2 / (3 * friction_coefficient * front_load) * jnp.abs(jnp.tan(angle)) * jnp.tan(angle)
            - cornering_stiffness**3 / (27 * friction_coefficient**2 * front_load**2) * jnp.tan(angle) ** 3
        )

    def calc_saturation_region(angle: jax.Array) -> jax.Array:
        """Calculate lateral force in the saturation region."""
        return -friction_coefficient * front_load * jnp.sign(angle)

    lateral_force = lax.cond(
        jnp.abs(adjusted_slip_angle) <= sliding_limit_angle,
        calc_linear_region,
        calc_saturation_region,
        adjusted_slip_angle,
    )

    return lateral_force
