"""Rear tire dynamics model.

This module contains functions for calculating the rear tire dynamics based on
the model described in 'Dynamics And Control Of Drifting In Automobiles'
(Hindiyeh, 2013).

The implementation follows the original MATLAB model's equations while providing
JAX compatibility for GPU acceleration and automatic differentiation.
"""

import jax
import jax.lax as lax
import jax.numpy as jnp
from jax import jit


@jit
def calculate_rear_tire_forces(
    longitudinal_velocity: jax.Array,
    wheel_velocity: jax.Array,
    slip_angle: jax.Array,
    friction_coefficient: jax.Array,
    sliding_friction_coefficient: jax.Array,
    rear_load: jax.Array,
    longitudinal_stiffness: jax.Array,
    cornering_stiffness: jax.Array,
) -> tuple[jax.Array, jax.Array]:
    """Calculate the longitudinal and lateral forces for the rear tire.

    This is a JAX implementation of the MATLAB tire_dyn_r.m function from the original model.

    Args:
        longitudinal_velocity: Vehicle longitudinal velocity in m/s.
            (Engineering variable: v_x)
        wheel_velocity: Wheel longitudinal velocity in m/s.
            (Engineering variable: wheel_vx)
        slip_angle: Angle between the tire's heading and its actual direction of travel, in radians.
            (Engineering variable: alpha)
        friction_coefficient: Tire-road friction coefficient (dimensionless).
            (Engineering variable: mu)
        sliding_friction_coefficient: Sliding friction coefficient (dimensionless).
            (Engineering variable: mu_slide)
        rear_load: Normal load on the rear tire in Newtons.
            (Engineering variable: load_r)
        longitudinal_stiffness: Tire longitudinal stiffness in N/unit slip.
            (Engineering variable: C_x)
        cornering_stiffness: Tire cornering stiffness in N/rad.
            (Engineering variable: C_alpha)

    Returns:
        longitudinal_force: Longitudinal force generated by the rear tire in Newtons.
            (Engineering variable: Fx)
        lateral_force: Lateral force generated by the rear tire in Newtons.
            (Engineering variable: Fy)
    """
    # Calculate longitudinal wheel slip (kappa)
    # Handle different cases for slip calculation

    # Case 1: Near-zero slip
    no_slip_condition = (jnp.abs(wheel_velocity - longitudinal_velocity) < 0.01) | (
        (jnp.abs(wheel_velocity) < 0.01) & (jnp.abs(longitudinal_velocity) < 0.01)
    )

    # Case 2: Infinite slip (vehicle stationary, wheel spinning)
    infinite_slip_condition = jnp.abs(longitudinal_velocity) < 0.01

    # Calculate longitudinal slip (kappa)
    longitudinal_slip = lax.cond(
        no_slip_condition,
        lambda _: jnp.zeros_like(longitudinal_velocity),  # zero slip
        lambda _: lax.cond(
            infinite_slip_condition,
            lambda _: jnp.sign(wheel_velocity) * jnp.inf,  # infinite slip case
            lambda _: (wheel_velocity - longitudinal_velocity)
            / jnp.abs(longitudinal_velocity),  # normal slip calculation
            None,
        ),
        None,
    )

    # Handle special case: infinite slip returns immediate solution
    def infinite_slip_case(_):
        # Handle infinite slip: saturated longitudinal force, zero lateral force
        return (
            jnp.sign(wheel_velocity) * friction_coefficient * rear_load,
            jnp.zeros_like(friction_coefficient),
        )

    # Normal processing for non-infinite slip cases
    def normal_slip_processing(_):
        # Determine spin direction (for handling negative slip)
        slip_sign = jnp.sign(longitudinal_slip)
        slip_magnitude = jnp.abs(longitudinal_slip)

        # Handle extreme slip angles (> pi/2, vehicle moving backwards)
        adjusted_slip_angle = lax.cond(
            jnp.abs(slip_angle) > jnp.pi / 2,
            lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
            lambda angle: angle,
            slip_angle,
        )

        # Combined slip parameter gamma
        gamma = jnp.sqrt(
            longitudinal_stiffness**2 * (slip_magnitude / (1 + slip_magnitude)) ** 2
            + cornering_stiffness**2
            * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude)) ** 2
        )

        # Force based on slip regime (linear vs. saturated)
        sliding_limit = 3 * friction_coefficient * rear_load

        # Linear region force calculation
        def calculate_linear_region_force(g: jax.Array) -> jax.Array:
            return (
                g
                - 1 / (3 * friction_coefficient * rear_load) * g**2
                + 1 / (27 * friction_coefficient**2 * rear_load**2) * g**3
            )

        # Saturation region force calculation
        def calculate_saturation_region_force(_: jax.Array) -> jax.Array:
            return sliding_friction_coefficient * rear_load

        # Total force magnitude based on regime
        force_magnitude = lax.cond(
            gamma <= sliding_limit,
            calculate_linear_region_force,
            calculate_saturation_region_force,
            gamma,
        )

        # Handle zero-gamma case to avoid division by zero
        def zero_gamma_case(_):
            return jnp.zeros_like(gamma), jnp.zeros_like(gamma)

        # Normal force calculation with non-zero gamma
        def nonzero_gamma_case(_):
            # Decompose force into longitudinal and lateral components
            fx = (
                longitudinal_stiffness
                / gamma
                * (slip_magnitude / (1 + slip_magnitude))
                * force_magnitude
                * slip_sign
            )

            fy = (
                -cornering_stiffness
                / gamma
                * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude))
                * force_magnitude
            )

            return fx, fy

        # Handle zero-gamma case
        return lax.cond(gamma == 0, zero_gamma_case, nonzero_gamma_case, None)

    # Branch for infinite slip vs normal processing
    return lax.cond(
        infinite_slip_condition & (jnp.abs(wheel_velocity) >= 0.01),
        infinite_slip_case,
        normal_slip_processing,
        None,
    )
