"""Front tire dynamics model.

This module contains functions for calculating the front tire dynamics based on
the model described in 'Dynamics And Control Of Drifting In Automobiles'
(Hindiyeh, 2013).

The implementation follows the original MATLAB model's equations while providing
JAX compatibility for GPU acceleration and automatic differentiation.
"""

from typing import Optional

import jax
import jax.numpy as jnp
from jax import jit

from slipjax.config import parameters
from slipjax.models.tire.base import BaseTireDynamics
from slipjax.utils.jax_helpers import jit_compatible_switch


class FrontTireDynamics(BaseTireDynamics):
    """Front tire dynamics model implementation."""
    
    def __init__(
        self, 
        cornering_stiffness: Optional[float] = None,
    ):
        """Initialize the front tire dynamics model.
        
        Args:
            cornering_stiffness: Tire cornering stiffness in N/rad. If None, use default value.
        """
        self.cornering_stiffness = cornering_stiffness or parameters.FRONT_CORNERING_STIFFNESS
    
    # Don't apply jit directly to the class method
    def __call__(
        self,
        slip_angle: jax.Array,
        slip_ratio: jax.Array,
        load: jax.Array,
        friction_coefficient: jax.Array,
    ) -> jax.Array:
        """Calculate the lateral force for the front tire given the slip angle.

        This is a JAX implementation of the MATLAB tire_dyn_f.m function from the original model.

        Args:
            slip_angle: Angle between the tire's heading and its actual direction of travel, in radians.
                (Engineering variable: alpha)
            slip_ratio: The slip ratio of the tire (dimensionless). Not used in this model but
                included for compatibility with the protocol.
            load: Normal load on the front tire in Newtons.
                (Engineering variable: load_f)
            friction_coefficient: Tire-road friction coefficient (dimensionless).
                (Engineering variable: mu)

        Returns:
            lateral_force: Lateral force generated by the front tire in Newtons.
                (Engineering variable: Fy)
        """
        # Handle extreme slip angles (> pi/2)
        adjusted_slip_angle = jit_compatible_switch(
            jnp.abs(slip_angle) > jnp.pi / 2,
            lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
            lambda angle: angle,
            slip_angle,
        )

        # Calculate the sliding limit angle (transition between regimes)
        sliding_limit_angle = jnp.arctan(
            3 * friction_coefficient * load / self.cornering_stiffness
        )

        # Calculate lateral force based on slip angle magnitude
        def calculate_linear_region_force(angle: jax.Array) -> jax.Array:
            """Calculate lateral force in the linear (non-saturated) region."""
            return (
                -self.cornering_stiffness * jnp.tan(angle)
                + self.cornering_stiffness**2
                / (3 * friction_coefficient * load)
                * jnp.abs(jnp.tan(angle))
                * jnp.tan(angle)
                - self.cornering_stiffness**3
                / (27 * friction_coefficient**2 * load**2)
                * jnp.tan(angle) ** 3
            )

        def calculate_saturation_region_force(angle: jax.Array) -> jax.Array:
            """Calculate lateral force in the saturation region."""
            return -friction_coefficient * load * jnp.sign(angle)

        lateral_force = jit_compatible_switch(
            jnp.abs(adjusted_slip_angle) <= sliding_limit_angle,
            calculate_linear_region_force,
            calculate_saturation_region_force,
            adjusted_slip_angle,
        )

        return lateral_force


# Create a JIT-compiled version of the __call__ method
def _jit_front_tire_call(self, slip_angle, slip_ratio, load, friction_coefficient):
    return self.__call__(slip_angle, slip_ratio, load, friction_coefficient)

# Apply JIT with static_argnums=0 to handle the self parameter
_jit_front_tire_call_jit = jit(_jit_front_tire_call, static_argnums=[0])

# Monkey patch the class with the JIT-compiled method
FrontTireDynamics.jit_call = _jit_front_tire_call_jit

# For backward compatibility
frontTireDynamics = FrontTireDynamics()


@jit
def calculate_front_tire_lateral_force(
    slip_angle: jax.Array,
    friction_coefficient: jax.Array,
    front_load: jax.Array,
    cornering_stiffness: jax.Array,
) -> jax.Array:
    """Legacy function for backward compatibility.
    
    Use FrontTireDynamics class for new code.
    """
    # Implement the calculations directly without creating a class instance
    # Handle extreme slip angles (> pi/2)
    adjusted_slip_angle = jit_compatible_switch(
        jnp.abs(slip_angle) > jnp.pi / 2,
        lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
        lambda angle: angle,
        slip_angle,
    )

    # Calculate the sliding limit angle (transition between regimes)
    sliding_limit_angle = jnp.arctan(
        3 * friction_coefficient * front_load / cornering_stiffness
    )

    # Calculate lateral force based on slip angle magnitude
    def calculate_linear_region_force(angle: jax.Array) -> jax.Array:
        """Calculate lateral force in the linear (non-saturated) region."""
        return (
            -cornering_stiffness * jnp.tan(angle)
            + cornering_stiffness**2
            / (3 * friction_coefficient * front_load)
            * jnp.abs(jnp.tan(angle))
            * jnp.tan(angle)
            - cornering_stiffness**3
            / (27 * friction_coefficient**2 * front_load**2)
            * jnp.tan(angle) ** 3
        )

    def calculate_saturation_region_force(angle: jax.Array) -> jax.Array:
        """Calculate lateral force in the saturation region."""
        return -friction_coefficient * front_load * jnp.sign(angle)

    lateral_force = jit_compatible_switch(
        jnp.abs(adjusted_slip_angle) <= sliding_limit_angle,
        calculate_linear_region_force,
        calculate_saturation_region_force,
        adjusted_slip_angle,
    )

    return lateral_force
