"""Rear tire dynamics model.

This module contains functions for calculating the rear tire dynamics based on
the model described in 'Dynamics And Control Of Drifting In Automobiles'
(Hindiyeh, 2013).

The implementation follows the original MATLAB model's equations while providing
JAX compatibility for GPU acceleration and automatic differentiation.
"""

from typing import Optional, Tuple

import jax
import jax.numpy as jnp
from jax import jit

from slipjax.config import parameters
from slipjax.models.tire.base import BaseTireDynamics
from slipjax.utils.jax_helpers import jit_compatible_switch, safe_division


class RearTireDynamics(BaseTireDynamics):
    """Rear tire dynamics model implementation."""
    
    def __init__(
        self, 
        cornering_stiffness: Optional[float] = None,
        longitudinal_stiffness: Optional[float] = None,
    ):
        """Initialize the rear tire dynamics model.
        
        Args:
            cornering_stiffness: Tire cornering stiffness in N/rad. If None, use default value.
            longitudinal_stiffness: Tire longitudinal stiffness in N/unit slip. If None, use default value.
        """
        self.cornering_stiffness = cornering_stiffness or parameters.REAR_CORNERING_STIFFNESS
        # Default value for longitudinal stiffness (not in parameters yet)
        self._default_longitudinal_stiffness = 3000.0
        self.longitudinal_stiffness = longitudinal_stiffness or self._default_longitudinal_stiffness
    
    # Don't apply jit directly to the class method
    def __call__(
        self,
        slip_angle: jax.Array,
        slip_ratio: jax.Array,
        load: jax.Array,
        friction_coefficient: jax.Array,
    ) -> jax.Array:
        """Calculate the lateral force for the rear tire.
        
        This is a simplified interface that only returns the lateral force component,
        following the BaseTireDynamics interface. For both longitudinal and lateral forces,
        use calculate_forces() method.
        
        Args:
            slip_angle: Angle between the tire's heading and its actual direction of travel, in radians.
            slip_ratio: The slip ratio of the tire (dimensionless).
            load: Normal load on the rear tire in Newtons.
            friction_coefficient: Tire-road friction coefficient.
            
        Returns:
            The lateral force in Newtons.
        """
        # For this simplified interface, we assume longitudinal velocity is 1.0 and
        # calculate wheel velocity from slip_ratio
        longitudinal_velocity = jnp.ones_like(slip_angle)
        wheel_velocity = longitudinal_velocity * (1.0 + slip_ratio)
        sliding_friction_coefficient = 0.8 * friction_coefficient  # Typical value
        
        _, lateral_force = self.calculate_forces(
            longitudinal_velocity,
            wheel_velocity,
            slip_angle,
            friction_coefficient,
            sliding_friction_coefficient,
            load,
        )
        
        return lateral_force
    
    # Don't apply jit directly to the class method
    def calculate_forces(
        self,
        longitudinal_velocity: jax.Array,
        wheel_velocity: jax.Array,
        slip_angle: jax.Array,
        friction_coefficient: jax.Array,
        sliding_friction_coefficient: jax.Array,
        load: jax.Array,
    ) -> Tuple[jax.Array, jax.Array]:
        """Calculate the longitudinal and lateral forces for the rear tire.

        This is a JAX implementation of the MATLAB tire_dyn_r.m function from the original model.

        Args:
            longitudinal_velocity: Vehicle longitudinal velocity in m/s.
                (Engineering variable: v_x)
            wheel_velocity: Wheel longitudinal velocity in m/s.
                (Engineering variable: wheel_vx)
            slip_angle: Angle between the tire's heading and its actual direction of travel, in radians.
                (Engineering variable: alpha)
            friction_coefficient: Tire-road friction coefficient (dimensionless).
                (Engineering variable: mu)
            sliding_friction_coefficient: Sliding friction coefficient (dimensionless).
                (Engineering variable: mu_slide)
            load: Normal load on the rear tire in Newtons.
                (Engineering variable: load_r)

        Returns:
            longitudinal_force: Longitudinal force generated by the rear tire in Newtons.
                (Engineering variable: Fx)
            lateral_force: Lateral force generated by the rear tire in Newtons.
                (Engineering variable: Fy)
        """
        # Calculate longitudinal wheel slip (kappa)
        # Handle different cases for slip calculation

        # Case 1: Near-zero slip
        no_slip_condition = (jnp.abs(wheel_velocity - longitudinal_velocity) < 0.01) | (
            (jnp.abs(wheel_velocity) < 0.01) & (jnp.abs(longitudinal_velocity) < 0.01)
        )

        # Case 2: Infinite slip (vehicle stationary, wheel spinning)
        infinite_slip_condition = jnp.abs(longitudinal_velocity) < 0.01

        # Calculate longitudinal slip (kappa) with nested conditionals
        def calculate_normal_slip(_):
            return safe_division(
                wheel_velocity - longitudinal_velocity,
                jnp.abs(longitudinal_velocity),
                jnp.sign(wheel_velocity) * jnp.inf
            )
            
        def calculate_slip(_):
            return jit_compatible_switch(
                infinite_slip_condition,
                lambda _: jnp.sign(wheel_velocity) * jnp.inf,  # infinite slip case
                calculate_normal_slip,  # normal slip calculation
                None,
            )
        
        longitudinal_slip = jit_compatible_switch(
            no_slip_condition,
            lambda _: jnp.zeros_like(longitudinal_velocity),  # zero slip
            calculate_slip,
            None,
        )

        # Handle special case: infinite slip returns immediate solution
        def infinite_slip_case(_):
            # Handle infinite slip: saturated longitudinal force, zero lateral force
            return (
                jnp.sign(wheel_velocity) * friction_coefficient * load,
                jnp.zeros_like(friction_coefficient),
            )

        # Normal processing for non-infinite slip cases
        def normal_slip_processing(_):
            # Determine spin direction (for handling negative slip)
            slip_sign = jnp.sign(longitudinal_slip)
            slip_magnitude = jnp.abs(longitudinal_slip)

            # Handle extreme slip angles (> pi/2, vehicle moving backwards)
            adjusted_slip_angle = jit_compatible_switch(
                jnp.abs(slip_angle) > jnp.pi / 2,
                lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
                lambda angle: angle,
                slip_angle,
            )

            # Combined slip parameter gamma
            gamma = jnp.sqrt(
                self.longitudinal_stiffness**2 * (slip_magnitude / (1 + slip_magnitude)) ** 2
                + self.cornering_stiffness**2
                * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude)) ** 2
            )

            # Force based on slip regime (linear vs. saturated)
            sliding_limit = 3 * friction_coefficient * load

            # Linear region force calculation
            def calculate_linear_region_force(g: jax.Array) -> jax.Array:
                return (
                    g
                    - 1 / (3 * friction_coefficient * load) * g**2
                    + 1 / (27 * friction_coefficient**2 * load**2) * g**3
                )

            # Saturation region force calculation
            def calculate_saturation_region_force(_: jax.Array) -> jax.Array:
                return sliding_friction_coefficient * load

            # Total force magnitude based on regime
            force_magnitude = jit_compatible_switch(
                gamma <= sliding_limit,
                calculate_linear_region_force,
                calculate_saturation_region_force,
                gamma,
            )

            # Handle zero-gamma case to avoid division by zero
            def zero_gamma_case(_):
                return jnp.zeros_like(gamma), jnp.zeros_like(gamma)

            # Normal force calculation with non-zero gamma
            def nonzero_gamma_case(_):
                # Decompose force into longitudinal and lateral components
                fx = (
                    self.longitudinal_stiffness
                    / gamma
                    * (slip_magnitude / (1 + slip_magnitude))
                    * force_magnitude
                    * slip_sign
                )

                fy = (
                    -self.cornering_stiffness
                    / gamma
                    * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude))
                    * force_magnitude
                )

                return fx, fy

            # Handle zero-gamma case
            return jit_compatible_switch(gamma == 0, zero_gamma_case, nonzero_gamma_case, None)

        # Branch for infinite slip vs normal processing
        return jit_compatible_switch(
            infinite_slip_condition & (jnp.abs(wheel_velocity) >= 0.01),
            infinite_slip_case,
            normal_slip_processing,
            None,
        )


# Create JIT-compiled versions of the methods
def _jit_rear_tire_call(self, slip_angle, slip_ratio, load, friction_coefficient):
    return self.__call__(slip_angle, slip_ratio, load, friction_coefficient)

def _jit_rear_tire_calculate_forces(self, longitudinal_velocity, wheel_velocity, slip_angle, 
                                    friction_coefficient, sliding_friction_coefficient, load):
    return self.calculate_forces(longitudinal_velocity, wheel_velocity, slip_angle, 
                               friction_coefficient, sliding_friction_coefficient, load)

# Apply JIT with static_argnums=0 to handle the self parameter
_jit_rear_tire_call_jit = jit(_jit_rear_tire_call, static_argnums=[0])
_jit_rear_tire_calculate_forces_jit = jit(_jit_rear_tire_calculate_forces, static_argnums=[0])

# Monkey patch the class with the JIT-compiled methods
RearTireDynamics.jit_call = _jit_rear_tire_call_jit
RearTireDynamics.jit_calculate_forces = _jit_rear_tire_calculate_forces_jit

# For backward compatibility
rearTireDynamics = RearTireDynamics()


@jit
def calculate_rear_tire_forces(
    longitudinal_velocity: jax.Array,
    wheel_velocity: jax.Array,
    slip_angle: jax.Array,
    friction_coefficient: jax.Array,
    sliding_friction_coefficient: jax.Array,
    rear_load: jax.Array,
    longitudinal_stiffness: jax.Array,
    cornering_stiffness: jax.Array,
) -> Tuple[jax.Array, jax.Array]:
    """Legacy function for backward compatibility.
    
    Use RearTireDynamics class for new code.
    """
    # Implement the calculations directly without creating a class instance
    # Calculate longitudinal wheel slip (kappa)
    # Handle different cases for slip calculation

    # Case 1: Near-zero slip
    no_slip_condition = (jnp.abs(wheel_velocity - longitudinal_velocity) < 0.01) | (
        (jnp.abs(wheel_velocity) < 0.01) & (jnp.abs(longitudinal_velocity) < 0.01)
    )

    # Case 2: Infinite slip (vehicle stationary, wheel spinning)
    infinite_slip_condition = jnp.abs(longitudinal_velocity) < 0.01

    # Calculate longitudinal slip (kappa) with nested conditionals
    def calculate_normal_slip(_):
        return safe_division(
            wheel_velocity - longitudinal_velocity,
            jnp.abs(longitudinal_velocity),
            jnp.sign(wheel_velocity) * jnp.inf
        )
        
    def calculate_slip(_):
        return jit_compatible_switch(
            infinite_slip_condition,
            lambda _: jnp.sign(wheel_velocity) * jnp.inf,  # infinite slip case
            calculate_normal_slip,  # normal slip calculation
            None,
        )
    
    longitudinal_slip = jit_compatible_switch(
        no_slip_condition,
        lambda _: jnp.zeros_like(longitudinal_velocity),  # zero slip
        calculate_slip,
        None,
    )

    # Handle special case: infinite slip returns immediate solution
    def infinite_slip_case(_):
        # Handle infinite slip: saturated longitudinal force, zero lateral force
        return (
            jnp.sign(wheel_velocity) * friction_coefficient * rear_load,
            jnp.zeros_like(friction_coefficient),
        )

    # Normal processing for non-infinite slip cases
    def normal_slip_processing(_):
        # Determine spin direction (for handling negative slip)
        slip_sign = jnp.sign(longitudinal_slip)
        slip_magnitude = jnp.abs(longitudinal_slip)

        # Handle extreme slip angles (> pi/2, vehicle moving backwards)
        adjusted_slip_angle = jit_compatible_switch(
            jnp.abs(slip_angle) > jnp.pi / 2,
            lambda angle: (jnp.pi - jnp.abs(angle)) * jnp.sign(angle),
            lambda angle: angle,
            slip_angle,
        )

        # Combined slip parameter gamma
        gamma = jnp.sqrt(
            longitudinal_stiffness**2 * (slip_magnitude / (1 + slip_magnitude)) ** 2
            + cornering_stiffness**2
            * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude)) ** 2
        )

        # Force based on slip regime (linear vs. saturated)
        sliding_limit = 3 * friction_coefficient * rear_load

        # Linear region force calculation
        def calculate_linear_region_force(g: jax.Array) -> jax.Array:
            return (
                g
                - 1 / (3 * friction_coefficient * rear_load) * g**2
                + 1 / (27 * friction_coefficient**2 * rear_load**2) * g**3
            )

        # Saturation region force calculation
        def calculate_saturation_region_force(_: jax.Array) -> jax.Array:
            return sliding_friction_coefficient * rear_load

        # Total force magnitude based on regime
        force_magnitude = jit_compatible_switch(
            gamma <= sliding_limit,
            calculate_linear_region_force,
            calculate_saturation_region_force,
            gamma,
        )

        # Handle zero-gamma case to avoid division by zero
        def zero_gamma_case(_):
            return jnp.zeros_like(gamma), jnp.zeros_like(gamma)

        # Normal force calculation with non-zero gamma
        def nonzero_gamma_case(_):
            # Decompose force into longitudinal and lateral components
            fx = (
                longitudinal_stiffness
                / gamma
                * (slip_magnitude / (1 + slip_magnitude))
                * force_magnitude
                * slip_sign
            )

            fy = (
                -cornering_stiffness
                / gamma
                * (jnp.tan(adjusted_slip_angle) / (1 + slip_magnitude))
                * force_magnitude
            )

            return fx, fy

        # Handle zero-gamma case
        return jit_compatible_switch(gamma == 0, zero_gamma_case, nonzero_gamma_case, None)

    # Branch for infinite slip vs normal processing
    return jit_compatible_switch(
        infinite_slip_condition & (jnp.abs(wheel_velocity) >= 0.01),
        infinite_slip_case,
        normal_slip_processing,
        None,
    )
